-- H:\Desarrollos\MyPython\Tkinter\ArkConInv\ArkConInvDB\database\schema.sql

-- 1-Empresas
CREATE TABLE IF NOT EXISTS ark_company (
    com_IDauto INTEGER PRIMARY KEY AUTOINCREMENT,
    com_Codigo TEXT NOT NULL UNIQUE,
    com_Descripcion TEXT,
    com_IDfiscal TEXT,
    com_Status INTEGER DEFAULT 1,
    com_DireccionF TEXT,
    com_DireccionL TEXT,
    com_Telefono1 TEXT,
    com_Telefono2 TEXT,
    com_Representante TEXT,
    com_TelefonoContacto TEXT,
    com_EmailContacto TEXT,
    com_EmailEmpresa TEXT,
    com_TipoContribuyente INTEGER,
    com_FechaCreacion TEXT DEFAULT (datetime('now')),
    com_SystemDate TEXT DEFAULT (date('now')),
    com_SystemTime TEXT DEFAULT (time('now')),
    com_NameMachine TEXT,
    com_UserCreator TEXT,
    com_LastUpdateDate TEXT,
    com_LastUpdateTime TEXT,
    com_UserLastUpdate TEXT
);

-- 2-Unidades Operativas
CREATE TABLE IF NOT EXISTS ark_unds_operativas (
    uo_id INTEGER PRIMARY KEY AUTOINCREMENT,
    uo_Codigo TEXT NOT NULL UNIQUE,
    uo_nombre TEXT NOT NULL,
    uo_descripcion TEXT,
    uo_empresa_id INTEGER NOT NULL,
    uo_dsn_name TEXT NOT NULL,
    uo_db_path TEXT,
    uo_active BOOLEAN DEFAULT 1,
    uo_SystemDate TEXT DEFAULT (date('now')),
    uo_SystemTime TEXT DEFAULT (time('now')),
    uo_NameMachine TEXT,
    uo_UserCreator TEXT,
    uo_LastUpdateDate TEXT,
    uo_LastUpdateTime TEXT,
    uo_LastMachine TEXT,
    uo_UserLastUpdate TEXT,  
    FOREIGN KEY (uo_empresa_id) REFERENCES ark_company (com_IDauto)
);

-- 3-Usuarios
CREATE TABLE IF NOT EXISTS ark_users (
    usr_IDauto INTEGER PRIMARY KEY AUTOINCREMENT,
    usr_Codigo TEXT NOT NULL UNIQUE,
    usr_login TEXT,
    usr_Descripcion TEXT,
    usr_Status INTEGER DEFAULT 1,
    usr_Telefono TEXT,
    usr_Cargo TEXT,
    usr_Rol TEXT,
    usr_EmailUsuario TEXT,
    usr_Password TEXT,
    usr_FechaCreacion TEXT DEFAULT (datetime('now')),
    id_company INTEGER,
    usr_SystemDate TEXT DEFAULT (date('now')),
    usr_SystemTime TEXT DEFAULT (time('now')),
    usr_NameMachine TEXT,
    usr_UserCreator TEXT,
    usr_LastUpdateDate TEXT,
    usr_LastUpdateTime TEXT,
    usr_LastMachine TEXT,
    usr_UserLastUpdate TEXT,    
    FOREIGN KEY (id_company) REFERENCES ark_company(com_IDauto)
);
-- 4-Categoria
CREATE TABLE IF NOT EXISTS ark_categoria (
    cat_IDauto INTEGER PRIMARY KEY AUTOINCREMENT,
    cat_codigo	TEXT NOT NULL UNIQUE,
    cat_descripcion	TEXT,
    cat_descripciondetallada	TEXT,
    cat_status	INTEGER,
    cat_porcentajeutilidad1	REAL,
    cat_porcentajeutilidad2	REAL,
    cat_porcentajeutilidad3	REAL,
    cat_porcentajeutilidad4	REAL,
    cat_porcentajeutilidad5	REAL,
    cat_porcentajeutilidad6	REAL,
    cat_comvtaproductos	INTEGER,
    cat_comcobroproductos	INTEGER,
    cat_clasificacion	INTEGER,
    cat_manejoinventario	INTEGER,
    cat_seriales	INTEGER,
    cat_vencimiento	INTEGER,
    cat_ofertas	INTEGER,
    cat_tallas_ejex	INTEGER,
    cat_tallas_ejey	INTEGER,
    cat_nroproductos	INTEGER,
    cat_depositos	INTEGER,
    cat_porcentajedescuento1	REAL,
    cat_porcentajedescuento2	REAL,
    cat_porcentajedescuento3	REAL,
    cat_porcentajedescuento4	REAL,
    cat_porcentajedescuento5	REAL,
    cat_porcentajedescuento6	REAL,
    cat_tallas_descrx	TEXT,
    cat_tallas_descry	TEXT,
    cat_indexporcent	INTEGER,
    cat_comisionvta1	REAL,
    cat_comisionvta2	REAL,
    cat_comisionvta3	REAL,
    cat_comisionvta4	REAL,
    cat_comisionvta5	REAL,
    cat_comisionvta6	REAL,
    cat_comisioncob1	REAL,
    cat_comisioncob2	REAL,
    cat_comisioncob3	REAL,
    cat_comisioncob4	REAL,
    cat_comisioncob5	REAL,
    cat_comisioncob6	REAL,
    cat_comisionvtamin	REAL,
    cat_comisioncobmin	REAL,
    cat_tolerancia	TEXT,
    cat_detalle_ejex	TEXT,
    cat_detalle_ejey	TEXT,
    cat_prefijo	TEXT,
    base_autoincrement	INTEGER,
    cat_psicotropico	INTEGER,
    cat_arancel	TEXT,
    cat_impresora	TEXT,
    cat_SystemDate TEXT DEFAULT (date('now')),
    cat_SystemTime TEXT DEFAULT (time('now')),
    cat_NameMachine TEXT,
    cat_UserCreator TEXT,
    cat_LastUpdateDate TEXT,
    cat_LastUpdateTime TEXT,
    cat_LastMachine TEXT,
    cat_UserLastUpdate TEXT
);
-- 5-Inventario
CREATE TABLE IF NOT EXISTS ark_inventario (
    inv_IDauto INTEGER PRIMARY KEY AUTOINCREMENT,
    inv_codigo	TEXT NOT NULL UNIQUE,
    inv_descripcion	TEXT,
    inv_categoria	TEXT,
    inv_descripciondetallada	TEXT,
    inv_vendedor	TEXT,
    inv_status	INTEGER,
    inv_unidad	TEXT,
    inv_tipocodigobarra	INTEGER,
    inv_imagen	BLOB,
    inv_sustituto1	TEXT,
    inv_sustituto2	TEXT,
    inv_sustituto3	TEXT,
    inv_referencia	TEXT,
    inv_marca	TEXT,
    inv_moneda	TEXT,
    inv_factorconversion	REAL,
    inv_undexistencia2	TEXT,
    inv_puesto	TEXT,
    inv_sujetoacomision	INTEGER,
    inv_montocomision	REAL,
    inv_cuentascontables	INTEGER,
    inv_pesoproducto	REAL,
    inv_diasdereposicion	INTEGER,
    inv_presentacion	INTEGER,
    inv_garantia	INTEGER,
    inv_sustituto4	TEXT,
    inv_sustituto5	TEXT,
    inv_montocomisionp	INTEGER,
    inv_depositos	INTEGER,
    inv_ofertas	INTEGER,
    inv_vencimientos	INTEGER,
    inv_clasificacion	INTEGER,
    inv_manejoinventario	INTEGER,
    inv_seriales	INTEGER,
    inv_creacion	TEXT,
    inv_inventarioinicialunidades	REAL,
    inv_inventarioinicialcosto	REAL,
    inv_capacidad	REAL,
    inv_existdecimal	INTEGER,
    inv_compuestoseriales	INTEGER,
    inv_vendedorfijo	TEXT,
    inv_vendedorfijoactivo	INTEGER,
    inv_modelo	TEXT,
    inv_subcategoria	TEXT,
    inv_pesoafectacosto	INTEGER,
    inv_impresora	TEXT,
    inv_base_autoincrement	INTEGER,
    inv_zextra1	REAL,
    inv_zextra2	REAL,
    inv_zextra3	REAL,
    inv_zextra4	REAL,
    inv_zextra5	REAL,
    inv_zextra6	REAL,
    inv_zextra1venta	INTEGER,
    inv_zextra2venta	INTEGER,
    inv_zextra3venta	INTEGER,
    inv_zextra4venta	INTEGER,
    inv_zextra5venta	INTEGER,
    inv_zextra6venta	INTEGER,
    inv_zextra1ventamod	INTEGER,
    inv_zextra2ventamod	INTEGER,
    inv_zextra3ventamod	INTEGER,
    inv_zextra4ventamod	INTEGER,
    inv_zextra5ventamod	INTEGER,
    inv_zextra6ventamod	INTEGER,
    inv_internet	INTEGER,
    inv_balanza	INTEGER,
    inv_codigobarra	INTEGER,
    inv_preciolista	INTEGER,
    inv_aprovechaporc	REAL,
    inv_arancel	TEXT,
    inv_posentrega	INTEGER,
    inv_cargosextras	TEXT,
    inv_SystemDate TEXT DEFAULT (date('now')),
    inv_SystemTime TEXT DEFAULT (time('now')),
    inv_NameMachine TEXT,
    inv_UserCreator TEXT,
    inv_LastUpdateDate TEXT,
    inv_LastUpdateTime TEXT,
    inv_LastMachine TEXT,
    inv_UserLastUpdate TEXT,
    FOREIGN KEY (inv_categoria) REFERENCES ark_categoria(cat_IDauto)
);
-- 6-Depositos
CREATE TABLE IF NOT EXISTS ark_depositos (
	dep_IDauto INTEGER PRIMARY KEY AUTOINCREMENT,
	dep_codigo	TEXT NOT NULL,
	dep_descripcion	TEXT,
	dep_status	INTEGER,
	dep_descripciondetallada	TEXT,
	dep_responsable	TEXT,
	dep_base_autoincrement	INTEGER,
	dep_code	TEXT,
	dep_serie	TEXT,
	dep_uo_origen	INTEGER,
    dep_uo_codigo TEXT,
    dep_uo_nombre TEXT,
	dep_SystemDate TEXT DEFAULT (date('now')),
	dep_SystemTime TEXT DEFAULT (time('now')),
	dep_NameMachine TEXT,
	dep_UserCreator TEXT,
	dep_LastUpdateDate TEXT,
	dep_LastUpdateTime TEXT,
	dep_LastMachine TEXT,
	dep_UserLastUpdate TEXT,
	FOREIGN KEY (dep_uo_origen) REFERENCES ark_unds_operativas(uo_id)
    
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_depositos_uo_codigo ON ark_depositos (dep_codigo, dep_uo_origen);